### ISSUE TITLE
Šitas pluginas yra toks nepopsovas nes jo ...

### ISSUE THREAD

**Issue by baltuonis** [andriusch/blueprints#1]
...pavadinimas dubliuojasi su Blueprint CSS karkasu. + machinist turi kažkokius tai ten blueprints. Kai įvedi guglej "rails blueprint" ne kvapo nėra šio plugino, netgi github ieškant jo greitai nerasi. 

Vertėtų labai pagalvot apie pavadinimo keitimą, nes daiktas šis vertas dėmesio.

Ir aprašymas turėtų būt ne "Another replacement for factories and fixtures", o "The ultimate DRY ( :D ) solution to loading test data in Rails."

Marketingo trūksta vienužodžiu :)

**Comment by andriusch** [comment]
Del pavadinimo - keisti jo nenoreciau, Blueprint CSS panasus pavadinimas, bet vis tik kitoks. Marketingo truksta, taciau as per daug ir nesistengiau reklamuot jo. Vistik pagrindine esme jo buvo palengvint mano darba.
Del aprasymo - pakeiciau jau :) veliau pakeisiu ir gemspec'e

**Comment by andriusch** [comment]
Del search'o tai labai keista, kai ieskai siaip, tai nera pirmam puslapy, kai ieskai tarp repositories, tai pats pirmas link'as. Gal cia nuo followeriu ir fork'u kazkaip priklauso...
